name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.HOSTINGER_HOST }} # Make sure HOSTINGER_HOST does not include any protocol prefix like 'ftp://' or 'sftp://'
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASS }}
          local-dir: ./ # Adjust if you want to deploy only specific directories
          server-dir: ./
  # Adjust based on where your files should go on Hostinger
